import '../../styles/globals.css';
import { initApp } from './app';
import { updateTopbarStrings } from './topbar';
import { updateAppearanceToggleStrings } from './appearance-toggle';
import { updateUndoStrings } from './undo-button';
import { updateSearchStrings } from '../features/search/search-results';
import { subscribe, getLocale } from '../lib/i18n';
import { renderColumns } from '../features/bookmarks/board';
import * as debug from '../lib/debug';

let bootstrapped = false;
let localeListenerInstalled = false;

function bootstrap(): void {
  if (bootstrapped) return;
  bootstrapped = true;
  void initApp();
  // v0.2.118: install the locale-change listener exactly once, after
  // initApp has had a chance to render the topbar / toggle / undo /
  // search / columns. Earlier `subscribe()` calls would no-op because
  // no DOM exists yet; the listener will still fire for the first
  // setLocale() that comes from chrome.storage.onChanged in apply.ts.
  if (!localeListenerInstalled) {
    localeListenerInstalled = true;
    installLocaleListener();
  }
}

/** v0.2.118: re-paint every locale-sensitive DOM node when the user
 *  changes the language. Each module exposes a `updateXxxStrings()`
 *  that re-reads t() for the active locale; the special-folder column
 *  titles and the (potentially open) settings panel need a full
 *  rebuild because their content is generated by renderColumns() and
 *  the settings panel's per-tab renderers.
 *
 *  Settings panel rerender is opt-in: if the panel is closed (#sp-content
 *  is absent), we skip it. The next openSettingsPanel() call will pick
 *  up the new locale naturally because renderContent reads t() at
 *  render time.
 *
 *  Returns immediately if the locale hasn't changed (subscriber sanity). */
function applyLocaleToDom(): void {
  const locale = getLocale();
  debug.log('i18n', 'applyLocaleToDom', { locale });

  // 1. Static topbar (search placeholder / aria, settings button).
  updateTopbarStrings();

  // 2. Dark-mode toggle tooltip + aria.
  updateAppearanceToggleStrings();

  // 3. Undo button label + count interpolation.
  updateUndoStrings();

  // 4. Search results footer (keyboard hints). updateSearchStrings is
  //    a no-op until search has been attached.
  updateSearchStrings();

  // 5. Re-render the bookmark columns so special-folder titles track
  //    the new locale. renderColumns is async but we don't need to
  //    await it for the user-facing repaint to feel immediate; the
  //    column list is brief and the per-folder title text dominates.
  void renderColumns();

  // 6. If the settings panel is open, re-render its content + nav so
  //    tab labels, form labels, and theme descriptions refresh.
  const content = document.getElementById('sp-content');
  const nav = document.querySelector<HTMLElement>('.sp-nav');
  if (content) {
    // The panel's `renderContent` is a module-private function, so we
    // trigger a full close+open. The panel's storage listener is torn
    // down on close and re-installed on open, so we don't leak.
    import('./settings-panel').then((mod) => {
      mod.closeSettingsPanel();
      // Reopen on the next frame to let the close animation play.
      requestAnimationFrame(() => mod.openSettingsPanel());
    });
  }
  void nav; // nav will be re-rendered inside openSettingsPanel
}

/** Subscribe to i18n module changes. The `subscribe` callback is called
 *  on every `setLocale()` and `initLocale()` invocation, with the
 *  caller responsible for short-circuiting no-op changes. */
function installLocaleListener(): void {
  subscribe(() => applyLocaleToDom());
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', bootstrap, { once: true });
} else {
  bootstrap();
}

console.log('newtab01 newtab loaded');
